-- FEATURE 6 ROLLBACK: Donor Retention Nudges
-- One-step removal script.
-- Safe to run multiple times.

BEGIN;

-- 1) Remove trigger from appointments first.
DROP TRIGGER IF EXISTS trg_check_achievements ON appointments;

-- 2) Remove feature functions.
DROP FUNCTION IF EXISTS check_and_unlock_achievements() CASCADE;
DROP FUNCTION IF EXISTS send_nudge_notification(UUID, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS unlock_achievement(UUID, TEXT, TEXT) CASCADE;

-- 3) Remove feature views.
DROP VIEW IF EXISTS vw_donor_profile_summary;
DROP VIEW IF EXISTS vw_inactive_donors;
DROP VIEW IF EXISTS vw_top_donors;
DROP VIEW IF EXISTS vw_donor_stats;

-- 4) Optional cleanup of notifications generated by this feature.
DELETE FROM notifications
WHERE event_type IN ('achievement_unlocked', 'nudge_campaign');

-- 5) Remove feature tables.
DROP TABLE IF EXISTS donor_nudge_campaigns;
DROP TABLE IF EXISTS donor_achievements;

COMMIT;
