import React from "react";
import { TouchableOpacity, Text, Alert, Share, Linking } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

interface CalendarExportButtonProps {
  appointmentId: string | number;
  patientName: string;
  appointmentDate: string;
  bloodGroup: string;
  backendUrl: string;
}

export const CalendarExportButton: React.FC<CalendarExportButtonProps> = ({
  appointmentId,
  patientName,
  appointmentDate,
  bloodGroup,
  backendUrl,
}) => {
  const toIcsDate = (dateObj: Date) => {
    const year = dateObj.getUTCFullYear();
    const month = String(dateObj.getUTCMonth() + 1).padStart(2, "0");
    const day = String(dateObj.getUTCDate()).padStart(2, "0");
    return `${year}${month}${day}`;
  };

  const escapeIcsText = (value = "") =>
    String(value)
      .replace(/\\/g, "\\\\")
      .replace(/;/g, "\\;")
      .replace(/,/g, "\\,")
      .replace(/\n/g, "\\n");

  const buildLocalIcs = () => {
    const start = new Date(`${appointmentDate}T00:00:00.000Z`);
    const end = new Date(start);
    end.setUTCDate(end.getUTCDate() + 1);

    const now = new Date();
    const dtStamp = `${now.getUTCFullYear()}${String(
      now.getUTCMonth() + 1,
    ).padStart(2, "0")}${String(now.getUTCDate()).padStart(2, "0")}T${String(
      now.getUTCHours(),
    ).padStart(2, "0")}${String(now.getUTCMinutes()).padStart(2, "0")}${String(
      now.getUTCSeconds(),
    ).padStart(2, "0")}Z`;

    const summary = `Blood Transfusion Appointment - ${patientName}`;
    const description = [
      "=== APPOINTMENT DETAILS ===",
      `Appointment ID: ${appointmentId}`,
      `Date: ${appointmentDate}`,
      `Patient: ${patientName}`,
      `Blood Group: ${bloodGroup}`,
      "",
      "Generated by Thalassemia Donor Cycle",
    ].join("\\n");

    return [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Thalassemia Donor Cycle//Appointments//EN",
      "CALSCALE:GREGORIAN",
      "METHOD:PUBLISH",
      "BEGIN:VEVENT",
      `UID:appointment-${appointmentId}@thalassemia-donor-cycle`,
      `DTSTAMP:${dtStamp}`,
      `DTSTART;VALUE=DATE:${toIcsDate(start)}`,
      `DTEND;VALUE=DATE:${toIcsDate(end)}`,
      `SUMMARY:${escapeIcsText(summary)}`,
      `DESCRIPTION:${escapeIcsText(description)}`,
      "END:VEVENT",
      "END:VCALENDAR",
      "",
    ].join("\r\n");
  };

  const handleDownloadICS = async () => {
    try {
      const icsUrl = `${backendUrl}/api/appointments?action=calendar&appointment_id=${encodeURIComponent(appointmentId)}`;

      // Fetch ICS file content
      let icsContent = "";
      try {
        const response = await fetch(icsUrl);
        if (response.ok) {
          icsContent = await response.text();
        }
      } catch {
        // Fall through to local ICS generator.
      }

      if (!icsContent || !icsContent.includes("BEGIN:VCALENDAR")) {
        icsContent = buildLocalIcs();
      }

      // Save to device
      const fileName = `appointment-${appointmentId}.ics`;
      const filePath = `${FileSystem.documentDirectory}${fileName}`;

      await FileSystem.writeAsStringAsync(filePath, icsContent);

      // Share the file
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(filePath, {
          mimeType: "text/calendar",
          UTI: "com.apple.calendar.item",
        });
      } else {
        Alert.alert("Success", "Calendar file saved to device");
      }
    } catch (error) {
      Alert.alert("Error", "Failed to download calendar file");
      console.error("Calendar export error:", error);
    }
  };

  const handleAddToGoogleCalendar = async () => {
    try {
      const start = new Date(`${appointmentDate}T00:00:00.000Z`);
      const end = new Date(start);
      end.setUTCDate(end.getUTCDate() + 1);

      const toCompact = (d: Date) => {
        const y = d.getUTCFullYear();
        const m = String(d.getUTCMonth() + 1).padStart(2, "0");
        const day = String(d.getUTCDate()).padStart(2, "0");
        return `${y}${m}${day}`;
      };

      const dates = `${toCompact(start)}/${toCompact(end)}`;
      const title = encodeURIComponent(
        `Blood Transfusion Appointment - ${patientName}`,
      );
      const description = encodeURIComponent(
        `=== APPOINTMENT DETAILS ===\n` +
          `Appointment ID: ${appointmentId}\n` +
          `Date: ${appointmentDate}\n` +
          `Patient: ${patientName}\n` +
          `Blood Group: ${bloodGroup}\n` +
          `\n=== INSTRUCTIONS ===\n` +
          `- Please arrive 15 minutes early\n` +
          `- Bring valid identification and medical records\n` +
          `- Inform staff if you have any health concerns\n` +
          `- This is a mandatory transfusion appointment\n` +
          `\n=== IMPORTANT ===\n` +
          `Do not miss this appointment as it is critical for your treatment.\n` +
          `If you need to cancel or reschedule, contact support immediately.\n` +
          `\n=== NEXT STEPS ===\n` +
          `1. Confirm the appointment date and time\n` +
          `2. Arrange transportation if needed\n` +
          `3. Review any pre-appointment requirements\n` +
          `4. Contact facility staff for any questions\n` +
          `\nGenerated by Thalassemia Donor Cycle - Healthcare Management System`,
      );

      const googleCalendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${description}`;

      await Linking.openURL(googleCalendarUrl);
    } catch (error) {
      Alert.alert("Error", "Failed to open Google Calendar");
      console.error("Google Calendar error:", error);
    }
  };

  return (
    <>
      <TouchableOpacity
        onPress={handleDownloadICS}
        activeOpacity={0.7}
        style={{
          backgroundColor: "#4F46E5",
          paddingHorizontal: 12,
          paddingVertical: 8,
          borderRadius: 8,
          marginRight: 8,
          marginBottom: 8,
        }}
      >
        <Text style={{ color: "#fff", fontSize: 12, fontWeight: "600" }}>
          📥 Download ICS
        </Text>
      </TouchableOpacity>

      <TouchableOpacity
        onPress={handleAddToGoogleCalendar}
        activeOpacity={0.7}
        style={{
          backgroundColor: "#10B981",
          paddingHorizontal: 12,
          paddingVertical: 8,
          borderRadius: 8,
          marginBottom: 8,
        }}
      >
        <Text style={{ color: "#fff", fontSize: 12, fontWeight: "600" }}>
          📅 Add to Calendar
        </Text>
      </TouchableOpacity>
    </>
  );
};
