/**
 * API: GET /api/appointments/calendar?appointment_id={id}
 * Purpose: Return an ICS file for one-tap calendar import on web/mobile clients
 */

import supabase from "../../utils/supabaseClient.js";

function toIcsDate(dateObj) {
  const year = dateObj.getUTCFullYear();
  const month = String(dateObj.getUTCMonth() + 1).padStart(2, "0");
  const day = String(dateObj.getUTCDate()).padStart(2, "0");
  return `${year}${month}${day}`;
}

function escapeIcsText(value = "") {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

export default async function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { appointment_id } = req.query;

  if (!appointment_id) {
    return res.status(400).json({ error: "Missing appointment_id" });
  }

  try {
    const { data: appt, error: apptError } = await supabase
      .from("appointments")
      .select("id, patient_id, donor_id, date, status")
      .eq("id", appointment_id)
      .single();

    if (apptError || !appt) {
      return res.status(404).json({ error: "Appointment not found" });
    }

    const [{ data: patient }, { data: donor }] = await Promise.all([
      supabase
        .from("patients")
        .select("name, blood_group")
        .eq("id", appt.patient_id)
        .single(),
      appt.donor_id
        ? supabase.from("donor").select("name").eq("id", appt.donor_id).single()
        : Promise.resolve({ data: null }),
    ]);

    const start = new Date(`${appt.date}T00:00:00.000Z`);
    const end = new Date(start);
    end.setUTCDate(end.getUTCDate() + 1); // all-day next-day boundary

    const dtStamp = new Date();
    const dtStampText = `${dtStamp.getUTCFullYear()}${String(
      dtStamp.getUTCMonth() + 1,
    ).padStart(
      2,
      "0",
    )}${String(dtStamp.getUTCDate()).padStart(2, "0")}T${String(
      dtStamp.getUTCHours(),
    ).padStart(
      2,
      "0",
    )}${String(dtStamp.getUTCMinutes()).padStart(2, "0")}${String(
      dtStamp.getUTCSeconds(),
    ).padStart(2, "0")}Z`;

    const summary = `Blood Transfusion Appointment - ${patient?.name || "Patient"}`;
    const description = [
      "=== APPOINTMENT DETAILS ===",
      `Appointment ID: ${appt.id}`,
      `Date: ${appt.date}`,
      `Status: ${appt.status || "Scheduled"}`,
      "",
      "=== PATIENT INFORMATION ===",
      `Name: ${patient?.name || "N/A"}`,
      `Blood Group: ${patient?.blood_group || "N/A"}`,
      "",
      "=== DONOR INFORMATION ===",
      `Assigned Donor: ${donor?.name || "Not yet assigned"}`,
      "",
      "=== INSTRUCTIONS ===",
      "- Please arrive 15 minutes early",
      "- Bring valid identification",
      "- Inform staff if you have any concerns",
      "- This is a mandatory transfusion appointment",
      "",
      "=== NEXT STEPS ===",
      "If you need to cancel or reschedule, contact support immediately.",
      "Do not miss this appointment as it is critical for your treatment.",
      "",
      "Generated by Thalassemia Donor Cycle - Healthcare Management System",
    ].join("\\n");

    const uid = `appointment-${appt.id}@thalassemia-donor-cycle`;
    const ics = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Thalassemia Donor Cycle//Appointments//EN",
      "CALSCALE:GREGORIAN",
      "METHOD:PUBLISH",
      "BEGIN:VEVENT",
      `UID:${uid}`,
      `DTSTAMP:${dtStampText}`,
      `DTSTART;VALUE=DATE:${toIcsDate(start)}`,
      `DTEND;VALUE=DATE:${toIcsDate(end)}`,
      `SUMMARY:${escapeIcsText(summary)}`,
      `DESCRIPTION:${escapeIcsText(description)}`,
      "END:VEVENT",
      "END:VCALENDAR",
      "",
    ].join("\r\n");

    res.setHeader("Content-Type", "text/calendar; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="appointment-${appt.id}.ics"`,
    );
    return res.status(200).send(ics);
  } catch (error) {
    console.error("❌ Error generating ICS:", error);
    return res.status(500).json({ error: "Failed to generate calendar file" });
  }
}
